version: '3.4'

services:
  trantritaiblog:
    image: ${DOCKER_REGISTRY-}trantritaiblog
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5001
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - 5001:80
      - 5000:443
    networks:
      - trantritainet
  datamodel:
    image: mysql/mysql-server
    restart: always
    ports:
      - 1433:1433
    environment:
      MYSQL_ROOT_PASSWORD: benztaii
    networks:
      - trantritainet
networks:
    trantritainet:
    